spring:
  application:
    name: saudacao-service
  profiles:
    active:
    - es
  config:
    import:
    - optional:configserver:http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  endpoint:
    health:
      show-details: always
saudacao-service:
  saudacao: Hello
  nome-padrao: World
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true